name: run-preprocessing

on:
  push:
    paths:
      - 'seeds_raw.csv'
      - 'preprocessing/automate_Sevyra-Nanda-Octavianti.py'
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn matplotlib seaborn

      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Sevyra-Nanda-Octavianti.py

      - name: Commit hasil preprocessing
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add preprocessing/iris_preprocessing.csv || echo "Nothing to add"
          git diff --cached --quiet && echo "No changes to commit" || (git commit -m "Update hasil preprocessing otomatis" && git push)
